name: genre-game-env
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - mlflow==2.16.0
      - scikit-learn==1.4.2
      - pandas==2.2.2
      - numpy==1.26.4
      - joblib==1.4.2
